import math

BOARD_SIZE_WIDTH = 500
BOARD_SIZE_HEIGHT = 350

CELL_SIZE = 15

NORMALIZED_WIDTH = round(BOARD_SIZE_WIDTH / CELL_SIZE)
NORMALIZED_HEIGHT = round(BOARD_SIZE_HEIGHT / CELL_SIZE)

GAME_PFS = 10

BOARD_COLOR = (111, 111, 111)
FOOD_COLOR = (0, 255, 0)
SNAKE_COLOR = (0, 0, 0)